"""Add contract models

Revision ID: 6f0618b3e263
Revises: ec061539678b
Create Date: 2026-03-07 16:06:13.916351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0618b3e263'
down_revision: Union[str, None] = 'ec061539678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_uploads_project_id'), 'contract_uploads', ['project_id'], unique=False)
    op.create_table('contract_risk_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_count_high', sa.Integer(), nullable=False),
    sa.Column('risk_count_medium', sa.Integer(), nullable=False),
    sa.Column('risk_count_low', sa.Integer(), nullable=False),
    sa.Column('risks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_terms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_uploads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_risk_reports')
    op.drop_index(op.f('ix_contract_uploads_project_id'), table_name='contract_uploads')
    op.drop_table('contract_uploads')
    # ### end Alembic commands ###