"""init all tables

Revision ID: 9043d9196d2c
Revises: 
Create Date: 2026-03-07 13:46:05.525622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9043d9196d2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('city_name', sa.String(length=50), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city_tier', sa.String(length=20), nullable=True),
    sa.Column('factor', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('labor_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('has_local_price', sa.Boolean(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_code')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('common_pitfall', sa.Text(), nullable=True),
    sa.Column('verify_method', sa.Text(), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_category'), 'glossary_terms', ['category'], unique=False)
    op.create_index(op.f('ix_glossary_terms_term'), 'glossary_terms', ['term'], unique=False)
    op.create_table('layout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('layout_type', sa.String(length=50), nullable=False),
    sa.Column('bedroom_count', sa.Integer(), nullable=False),
    sa.Column('living_count', sa.Integer(), nullable=False),
    sa.Column('bathroom_count', sa.Integer(), nullable=False),
    sa.Column('area_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('area_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_standard_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('pricing_mode', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_formula', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('risk_if_missing', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_pricing_standard_items_category'), 'pricing_standard_items', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('standard_item_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('material_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('labor_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accessory_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('loss_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('price_source', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['standard_item_id'], ['pricing_standard_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_city_code'), 'pricing_rules', ['city_code'], unique=False)
    op.create_table('renovation_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('city_name', sa.String(length=50), nullable=True),
    sa.Column('target_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('current_phase', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renovation_projects_user_id'), 'renovation_projects', ['user_id'], unique=False)
    op.create_table('room_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layout_template_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=30), nullable=False),
    sa.Column('area_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('default_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ceiling_height', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('door_count', sa.Integer(), nullable=False),
    sa.Column('window_count', sa.Integer(), nullable=False),
    sa.Column('window_area_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('default_floor', sa.String(length=20), nullable=True),
    sa.Column('default_wall', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['layout_template_id'], ['layout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)
    op.create_table('ai_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_table('budget_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('material_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('labor_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accessory_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contingency', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_schemes_project_id'), 'budget_schemes', ['project_id'], unique=False)
    op.create_table('checklist_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_records_project_id'), 'checklist_records', ['project_id'], unique=False)
    op.create_table('construction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('photos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_logs_project_id'), 'construction_logs', ['project_id'], unique=False)
    op.create_table('construction_phase_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_phase_records_project_id'), 'construction_phase_records', ['project_id'], unique=False)
    op.create_table('house_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('building_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('inner_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('layout_type', sa.String(length=50), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('building_age', sa.Integer(), nullable=True),
    sa.Column('is_elevator', sa.Boolean(), nullable=False),
    sa.Column('has_balcony', sa.Boolean(), nullable=False),
    sa.Column('balcony_count', sa.Integer(), nullable=False),
    sa.Column('bathroom_count', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('decoration_style', sa.String(length=50), nullable=True),
    sa.Column('tier_preference', sa.String(length=20), nullable=False),
    sa.Column('floor_preference', sa.String(length=20), nullable=False),
    sa.Column('special_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_profiles_project_id'), 'house_profiles', ['project_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payee', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_project_id'), 'payment_records', ['project_id'], unique=False)
    op.create_table('purchase_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('need_measure', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_records_project_id'), 'purchase_records', ['project_id'], unique=False)
    op.create_table('quote_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_uploads_project_id'), 'quote_uploads', ['project_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_session_id'), 'ai_messages', ['session_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('standard_item_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('material_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('accessory_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loss_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('original_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['budget_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_scheme_id'), 'budget_items', ['scheme_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=200), nullable=True),
    sa.Column('matched_std_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    op.create_table('quote_risk_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_count_high', sa.Integer(), nullable=False),
    sa.Column('risk_count_medium', sa.Integer(), nullable=False),
    sa.Column('risk_count_low', sa.Integer(), nullable=False),
    sa.Column('risks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_anomalies_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['renovation_projects.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house_profile_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=30), nullable=False),
    sa.Column('area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('perimeter', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ceiling_height', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('wall_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('door_count', sa.Integer(), nullable=False),
    sa.Column('window_count', sa.Integer(), nullable=False),
    sa.Column('window_area', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('has_floor_heating', sa.Boolean(), nullable=False),
    sa.Column('floor_material', sa.String(length=20), nullable=True),
    sa.Column('wall_material', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_profile_id'], ['house_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_house_profile_id'), 'rooms', ['house_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_house_profile_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('quote_risk_reports')
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_budget_items_scheme_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_ai_messages_session_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_quote_uploads_project_id'), table_name='quote_uploads')
    op.drop_table('quote_uploads')
    op.drop_index(op.f('ix_purchase_records_project_id'), table_name='purchase_records')
    op.drop_table('purchase_records')
    op.drop_index(op.f('ix_payment_records_project_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_house_profiles_project_id'), table_name='house_profiles')
    op.drop_table('house_profiles')
    op.drop_index(op.f('ix_construction_phase_records_project_id'), table_name='construction_phase_records')
    op.drop_table('construction_phase_records')
    op.drop_index(op.f('ix_construction_logs_project_id'), table_name='construction_logs')
    op.drop_table('construction_logs')
    op.drop_index(op.f('ix_checklist_records_project_id'), table_name='checklist_records')
    op.drop_table('checklist_records')
    op.drop_index(op.f('ix_budget_schemes_project_id'), table_name='budget_schemes')
    op.drop_table('budget_schemes')
    op.drop_index(op.f('ix_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_table('room_templates')
    op.drop_index(op.f('ix_renovation_projects_user_id'), table_name='renovation_projects')
    op.drop_table('renovation_projects')
    op.drop_index(op.f('ix_pricing_rules_city_code'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pricing_standard_items_category'), table_name='pricing_standard_items')
    op.drop_table('pricing_standard_items')
    op.drop_table('layout_templates')
    op.drop_index(op.f('ix_glossary_terms_term'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_category'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_table('city_factors')
    # ### end Alembic commands ###