"""Add addon fields to payments

Revision ID: d054a00edbe8
Revises: 6f0618b3e263
Create Date: 2026-03-07 16:11:51.497913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd054a00edbe8'
down_revision: Union[str, None] = '6f0618b3e263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_records', sa.Column('is_addon', sa.Boolean(), nullable=False))
    op.add_column('payment_records', sa.Column('addon_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_records', 'addon_reason')
    op.drop_column('payment_records', 'is_addon')
    # ### end Alembic commands ###